name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: pnpm install

    - name: Run syncDatasources
      run: pnpm turbo run syncDatasources
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
